In [1]:
# This is my first Notebook!


In [2]:
from __future__ import print_function

%load_ext autoreload
%autoreload 2
import torch

In [3]:
x = torch.empty(5, 3)
print(x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [60]:
x = torch.randn(5,3)
print(x)

tensor([[ 1.0597, -1.1645, -0.6135],
        [-0.3498,  0.9328,  0.4379],
        [-0.2349,  0.2810, -0.3971],
        [ 0.7595, -0.3702, -0.1251],
        [ 0.0896, -1.4874,  1.1326]])


In [63]:
x.size()

torch.Size([5, 3])

In [5]:
x = torch.rand(5,3)
print(x)

tensor([[0.5883, 0.1643, 0.2345],
        [0.2173, 0.5003, 0.9018],
        [0.6178, 0.5684, 0.8633],
        [0.9052, 0.1853, 0.5530],
        [0.6694, 0.8018, 0.5374]])


In [6]:
x = torch.zeros(5,3, dtype=torch.long)
print(x);

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [48]:
x = torch.tensor([5.5,3]);
print(x);


tensor([5.5000, 3.0000])


In [49]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [50]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.8316, -0.6550,  0.5273],
        [-1.0579, -0.4956, -1.0440],
        [ 0.9744, -2.6137,  1.2637],
        [-0.3816, -1.5895,  0.3194],
        [-0.6409,  0.1289, -0.3893]])


In [51]:
print(x.size())

torch.Size([5, 3])


In [59]:
num_features = 1;
for s in x.size()[1:]:
            num_features *= s
            print(num_features)

3


In [11]:
y = torch.rand(5,3)
print( x + y )

tensor([[ 2.5202,  0.8082,  0.5714],
        [-0.8530,  0.8128,  1.3785],
        [-0.9104,  1.0881,  1.4302],
        [ 1.7111, -0.3070,  1.6053],
        [ 0.3577,  0.3954,  1.2936]])


In [12]:
result = torch.empty(5,3);
print(result);
torch.add(x,y, out=result)
print(result)

tensor([[0.0000e+00, 0.0000e+00, 1.4173e-33],
        [8.5920e+09, 5.6052e-45, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 1.4144e-33]])
tensor([[ 2.5202,  0.8082,  0.5714],
        [-0.8530,  0.8128,  1.3785],
        [-0.9104,  1.0881,  1.4302],
        [ 1.7111, -0.3070,  1.6053],
        [ 0.3577,  0.3954,  1.2936]])


In [13]:
y.add(x)
print(y)

tensor([[0.9874, 0.5326, 0.0196],
        [0.4121, 0.1046, 0.0566],
        [0.3131, 0.2323, 0.3371],
        [0.8929, 0.5673, 0.5178],
        [0.1320, 0.5793, 0.8057]])


In [14]:
y.add(-x)

tensor([[-0.5454,  0.2571, -0.5322],
        [ 1.6771, -0.6037, -1.2653],
        [ 1.5366, -0.6234, -0.7560],
        [ 0.0746,  1.4416, -0.5697],
        [-0.0937,  0.7632,  0.3178]])

In [15]:
y.add(x)

tensor([[ 2.5202,  0.8082,  0.5714],
        [-0.8530,  0.8128,  1.3785],
        [-0.9104,  1.0881,  1.4302],
        [ 1.7111, -0.3070,  1.6053],
        [ 0.3577,  0.3954,  1.2936]])

In [16]:
print(y)

tensor([[0.9874, 0.5326, 0.0196],
        [0.4121, 0.1046, 0.0566],
        [0.3131, 0.2323, 0.3371],
        [0.8929, 0.5673, 0.5178],
        [0.1320, 0.5793, 0.8057]])


In [17]:
print(x)

tensor([[ 1.5328,  0.2755,  0.5518],
        [-1.2650,  0.7083,  1.3219],
        [-1.2235,  0.8558,  1.0931],
        [ 0.8183, -0.8743,  1.0875],
        [ 0.2257, -0.1839,  0.4879]])


In [18]:
y.add(-x)

tensor([[-0.5454,  0.2571, -0.5322],
        [ 1.6771, -0.6037, -1.2653],
        [ 1.5366, -0.6234, -0.7560],
        [ 0.0746,  1.4416, -0.5697],
        [-0.0937,  0.7632,  0.3178]])

In [19]:
print(y)

tensor([[0.9874, 0.5326, 0.0196],
        [0.4121, 0.1046, 0.0566],
        [0.3131, 0.2323, 0.3371],
        [0.8929, 0.5673, 0.5178],
        [0.1320, 0.5793, 0.8057]])


In [20]:
print(x[:,1])

tensor([ 0.2755,  0.7083,  0.8558, -0.8743, -0.1839])


In [21]:
print(x)

tensor([[ 1.5328,  0.2755,  0.5518],
        [-1.2650,  0.7083,  1.3219],
        [-1.2235,  0.8558,  1.0931],
        [ 0.8183, -0.8743,  1.0875],
        [ 0.2257, -0.1839,  0.4879]])


In [22]:
a = torch.ones(5)

In [23]:
b = a.numpy()

In [24]:
print(b)


[1. 1. 1. 1. 1.]


In [25]:
print(a)

tensor([1., 1., 1., 1., 1.])


In [26]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [27]:
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [28]:
import numpy as np

In [29]:
a = np.ones(5)
b = torch.from_numpy(a)

In [30]:
np.add(a, 1, out=a)

array([2., 2., 2., 2., 2.])

In [31]:
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [32]:
torch.cuda.is_available

<function torch.cuda.is_available()>

In [33]:
print(torch.cuda.is_available())

False


In [34]:
x = torch.ones(2,2, requires_grad=True)

In [35]:
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [36]:
y = x+2

In [37]:
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [38]:
print(y.grad_fn)

In [39]:
z = y * y * 3

In [40]:
print(z)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>)


In [41]:
out = z.mean()

In [42]:
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


In [43]:
out.backward()