<a href="https://colab.research.google.com/github/njho/Notebooks/blob/master/My_First_Notebook.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
# This is my first Notebook!


In [0]:
# # http://pytorch.org/
# from os.path import exists
# from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
# platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
# cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
# accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'

# !pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.4.1-{platform}-linux_x86_64.whl torchvision
# import torch

In [96]:
from __future__ import print_function

%load_ext autoreload
%autoreload 2
import torch

The autoreload extension is already loaded. To reload it, use:
  %reload_ext autoreload


In [0]:
# http://pytorch.org/
from os.path import exists
from wheel.pep425tags import get_abbr_impl, get_impl_ver, get_abi_tag
platform = '{}{}-{}'.format(get_abbr_impl(), get_impl_ver(), get_abi_tag())
cuda_output = !ldconfig -p|grep cudart.so|sed -e 's/.*\.\([0-9]*\)\.\([0-9]*\)$/cu\1\2/'
accelerator = cuda_output[0] if exists('/dev/nvidia0') else 'cpu'

!pip install -q http://download.pytorch.org/whl/{accelerator}/torch-0.4.1-{platform}-linux_x86_64.whl torchvision
import torch

In [98]:
x = torch.empty(5, 3)
print(x)

tensor([[1.6378e-37, 0.0000e+00, 4.4842e-44],
        [0.0000e+00,        nan, 2.4310e-37],
        [2.6826e+23, 4.2886e-08, 1.3662e-05],
        [5.3690e-05, 2.6332e+20, 4.2654e-08],
        [1.0562e-05, 5.3977e-05, 1.9633e+34]])


In [99]:
x = torch.randn(5,3)
print(x)

tensor([[ 1.4921, -0.2372,  0.2862],
        [ 0.4508,  0.9462, -0.8951],
        [ 0.1714,  1.0400, -0.1521],
        [-1.4312, -0.8684,  0.8122],
        [-0.7242,  0.4831, -0.7338]])


In [100]:
x.size()

torch.Size([5, 3])

In [101]:
x = torch.rand(5,3)
print(x)

tensor([[0.3136, 0.3695, 0.2987],
        [0.1880, 0.9486, 0.4408],
        [0.5178, 0.2826, 0.9189],
        [0.2077, 0.6097, 0.4125],
        [0.1533, 0.1409, 0.1049]])


In [102]:
x = torch.zeros(5,3, dtype=torch.long)
print(x);

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [103]:
x = torch.tensor([5.5,3]);
print(x);


tensor([5.5000, 3.0000])


In [104]:
x = x.new_ones(5,3, dtype=torch.double)
print(x)

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)


In [105]:
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 0.9550, -0.6385,  0.5562],
        [-0.3965,  0.3873, -0.7307],
        [ 0.0476,  1.9993,  0.0156],
        [ 0.7437, -1.3766, -2.2663],
        [-0.2656, -1.5316, -0.9865]])


In [106]:
print(x.size())

torch.Size([5, 3])


In [107]:
num_features = 1;
for s in x.size()[1:]:
            num_features *= s
            print(num_features)

3


In [108]:
y = torch.rand(5,3)
print( x + y )

tensor([[ 1.1268, -0.4226,  0.7637],
        [ 0.4963,  0.6107, -0.3762],
        [ 0.8945,  2.5993,  0.3913],
        [ 1.2126, -0.8410, -1.7808],
        [ 0.5323, -1.4352, -0.8948]])


In [109]:
result = torch.empty(5,3);
print(result);
torch.add(x,y, out=result)
print(result)

tensor([[ 4.5859e-38,  0.0000e+00,  4.4842e-44],
        [ 0.0000e+00,         nan, -3.7619e-01],
        [ 2.6826e+23,  4.2886e-08,  1.3662e-05],
        [ 5.3690e-05,  2.6332e+20,  4.2654e-08],
        [ 1.0562e-05,  5.3977e-05, -8.9484e-01]])
tensor([[ 1.1268, -0.4226,  0.7637],
        [ 0.4963,  0.6107, -0.3762],
        [ 0.8945,  2.5993,  0.3913],
        [ 1.2126, -0.8410, -1.7808],
        [ 0.5323, -1.4352, -0.8948]])


In [110]:
y.add(x)
print(y)

tensor([[0.1718, 0.2159, 0.2075],
        [0.8928, 0.2235, 0.3545],
        [0.8470, 0.6000, 0.3757],
        [0.4690, 0.5356, 0.4854],
        [0.7978, 0.0964, 0.0916]])


In [111]:
y.add(-x)

tensor([[-0.7832,  0.8545, -0.3487],
        [ 1.2894, -0.1638,  1.0852],
        [ 0.7994, -1.3994,  0.3601],
        [-0.2747,  1.9122,  2.7517],
        [ 1.0634,  1.6280,  1.0781]])

In [112]:
y.add(x)

tensor([[ 1.1268, -0.4226,  0.7637],
        [ 0.4963,  0.6107, -0.3762],
        [ 0.8945,  2.5993,  0.3913],
        [ 1.2126, -0.8410, -1.7808],
        [ 0.5323, -1.4352, -0.8948]])

In [113]:
print(y)

tensor([[0.1718, 0.2159, 0.2075],
        [0.8928, 0.2235, 0.3545],
        [0.8470, 0.6000, 0.3757],
        [0.4690, 0.5356, 0.4854],
        [0.7978, 0.0964, 0.0916]])


In [114]:
print(x)

tensor([[ 0.9550, -0.6385,  0.5562],
        [-0.3965,  0.3873, -0.7307],
        [ 0.0476,  1.9993,  0.0156],
        [ 0.7437, -1.3766, -2.2663],
        [-0.2656, -1.5316, -0.9865]])


In [115]:
y.add(-x)

tensor([[-0.7832,  0.8545, -0.3487],
        [ 1.2894, -0.1638,  1.0852],
        [ 0.7994, -1.3994,  0.3601],
        [-0.2747,  1.9122,  2.7517],
        [ 1.0634,  1.6280,  1.0781]])

In [116]:
print(y)

tensor([[0.1718, 0.2159, 0.2075],
        [0.8928, 0.2235, 0.3545],
        [0.8470, 0.6000, 0.3757],
        [0.4690, 0.5356, 0.4854],
        [0.7978, 0.0964, 0.0916]])


In [117]:
print(x[:,1])

tensor([-0.6385,  0.3873,  1.9993, -1.3766, -1.5316])


In [118]:
print(x)

tensor([[ 0.9550, -0.6385,  0.5562],
        [-0.3965,  0.3873, -0.7307],
        [ 0.0476,  1.9993,  0.0156],
        [ 0.7437, -1.3766, -2.2663],
        [-0.2656, -1.5316, -0.9865]])


In [0]:
a = torch.ones(5)

In [0]:
b = a.numpy()

In [121]:
print(b)


[1. 1. 1. 1. 1.]


In [122]:
print(a)

tensor([1., 1., 1., 1., 1.])


In [123]:
a.add_(1)

tensor([2., 2., 2., 2., 2.])

In [124]:
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [0]:
import numpy as np

In [0]:
a = np.ones(5)
b = torch.from_numpy(a)

In [127]:
np.add(a, 1, out=a)

array([2., 2., 2., 2., 2.])

In [128]:
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [129]:
torch.cuda.is_available

<function torch.cuda.is_available>

In [130]:
print(torch.cuda.is_available())

False


In [0]:
x = torch.ones(2,2, requires_grad=True)

In [132]:
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [0]:
y = x+2

In [134]:
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward>)


In [135]:
print(y.grad_fn)

In [0]:
z = y * y * 3

In [137]:
print(z)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>)


In [0]:
out = z.mean()

In [139]:
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward>) tensor(27., grad_fn=<MeanBackward1>)


In [0]:
out.backward()